<a href="https://colab.research.google.com/github/agentshanz/StudentGradePredictModel/blob/main/StudentGradePredictModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('student_performance_dataset.csv')

In [ ]:
df

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [ ]:
df.count()

student_id                    1000
gender                        1000
study_time_hours              1000
attendance_percent            1000
sleep_hours                   1000
parental_education             898
internet_access               1000
extracurricular_activities    1000
part_time_job                 1000
previous_grade                1000
final_exam_score              1000
final_grade                   1000
dtype: int64

In [ ]:
df.head()

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D

In [ ]:
df.describe()

,student_id,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,3.570700,85.092300,6.799500,69.740900,83.543500
std,288.819436,1.478559,9.270685,1.203527,12.613425,10.341333
min,1.000000,0.500000,54.800000,3.200000,31.300000,46.800000
25%,250.750000,2.600000,78.800000,5.900000,61.000000,76.075000
50%,500.500000,3.600000,85.200000,6.800000,69.600000,83.800000
75%,750.250000,4.500000,91.900000,7.600000,78.400000,91.525000
max,1000.000000,8.100000,100.000000,10.000000,100.000000,100.000000

In [ ]:
df.isna().sum()

student_id                      0
gender                          0
study_time_hours                0
attendance_percent              0
sleep_hours                     0
parental_education            102
internet_access                 0
extracurricular_activities      0
part_time_job                   0
previous_grade                  0
final_exam_score                0
final_grade                     0
dtype: int64

In [ ]:
df = df.drop('parental_education',axis=1)

In [ ]:
df

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Yes,No,No,45.4,70.4,C

In [ ]:
df.isna().sum()

student_id                    0
gender                        0
study_time_hours              0
attendance_percent            0
sleep_hours                   0
internet_access               0
extracurricular_activities    0
part_time_job                 0
previous_grade                0
final_exam_score              0
final_grade                   0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lr = LabelEncoder()

In [ ]:
x = df.drop('final_grade',axis=1)

In [ ]:
x

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score
0,1,1,4.0,98.0,6.5,1,1,0,76.9,100.0
1,2,0,6.3,100.0,5.7,1,1,1,75.5,100.0
2,3,1,4.9,85.3,7.9,1,0,1,88.5,97.3
3,4,1,2.6,77.5,8.0,1,1,0,85.1,83.8
4,5,1,2.2,89.6,4.6,1,0,1,61.8,68.3
...,...,...,...,...,...,...,...,...,...,...
995,996,1,2.8,75.4,8.2,1,1,0,60.5,70.7
996,997,1,6.7,88.4,7.1,0,1,0,82.2,99.5
997,998,0,2.6,84.5,8.0,1,1,1,65.2,79.2
998,999,0,4.6,85.3,8.1,0,0,1,52.2,82.2
999,1000,1,3.9,77.4,6.1,1,0,0,45.4,70.4

In [ ]:
df['gender'] = lr.fit_transform(df['gender'])

In [ ]:
lr.classes_

array(['No', 'Yes'], dtype=object)

In [ ]:
df['internet_access'] = lr.fit_transform(df['internet_access'])

In [ ]:
df['extracurricular_activities'] = lr.fit_transform(df['extracurricular_activities'])

In [ ]:
df['part_time_job'] = lr.fit_transform(df['part_time_job'])

In [ ]:
df

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,1,4.0,98.0,6.5,1,1,0,76.9,100.0,A
1,2,0,6.3,100.0,5.7,1,1,1,75.5,100.0,A
2,3,1,4.9,85.3,7.9,1,0,1,88.5,97.3,A
3,4,1,2.6,77.5,8.0,1,1,0,85.1,83.8,B
4,5,1,2.2,89.6,4.6,1,0,1,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...
995,996,1,2.8,75.4,8.2,1,1,0,60.5,70.7,C
996,997,1,6.7,88.4,7.1,0,1,0,82.2,99.5,A
997,998,0,2.6,84.5,8.0,1,1,1,65.2,79.2,C
998,999,0,4.6,85.3,8.1,0,0,1,52.2,82.2,B
999,1000,1,3.9,77.4,6.1,1,0,0,45.4,70.4,C

In [ ]:
y = df['final_grade']

In [ ]:
y

0      A
1      A
2      A
3      B
4      D
      ..
995    C
996    A
997    C
998    B
999    C
Name: final_grade, Length: 1000, dtype: object

In [ ]:
x

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score
0,1,Male,4.0,98.0,6.5,Yes,Yes,No,76.9,100.0
1,2,Female,6.3,100.0,5.7,Yes,Yes,Yes,75.5,100.0
2,3,Male,4.9,85.3,7.9,Yes,No,Yes,88.5,97.3
3,4,Male,2.6,77.5,8.0,Yes,Yes,No,85.1,83.8
4,5,Male,2.2,89.6,4.6,Yes,No,Yes,61.8,68.3
...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Yes,Yes,No,60.5,70.7
996,997,Male,6.7,88.4,7.1,No,Yes,No,82.2,99.5
997,998,Female,2.6,84.5,8.0,Yes,Yes,Yes,65.2,79.2
998,999,Female,4.6,85.3,8.1,No,No,Yes,52.2,82.2
999,1000,Male,3.9,77.4,6.1,Yes,No,No,45.4,70.4

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.2)

In [ ]:
x_test

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score
506,507,0,5.1,80.6,7.7,1,0,0,51.1,74.5
660,661,0,4.5,85.0,8.2,1,0,0,71.9,95.2
769,770,1,5.0,78.8,4.8,1,0,0,83.5,98.4
317,318,1,1.4,96.1,8.0,0,1,0,75.7,79.2
334,335,0,4.0,90.1,9.1,1,0,0,69.9,88.7
...,...,...,...,...,...,...,...,...,...,...
39,40,1,5.6,65.3,7.4,1,1,0,85.5,91.6
214,215,1,4.6,83.2,4.5,1,1,0,58.0,84.7
657,658,1,3.4,86.5,7.1,1,1,0,95.5,100.0
206,207,0,4.2,89.4,6.7,1,1,1,79.7,100.0
237,238,0,5.5,78.3,8.5,1,0,0,73.4,84.4

In [ ]:
y_test

506    C
660    A
769    A
317    C
334    B
      ..
39     A
214    B
657    A
206    A
237    B
Name: final_grade, Length: 800, dtype: object

In [ ]:
x_train

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score
421,422,0,2.8,90.1,5.8,0,1,0,84.1,89.6
197,198,0,6.9,85.6,8.3,1,1,0,67.3,92.2
990,991,0,2.5,81.4,6.5,1,0,0,81.8,81.9
60,61,1,4.0,79.7,7.2,1,1,0,67.4,80.4
871,872,0,4.1,80.8,5.9,1,1,1,76.9,92.6
...,...,...,...,...,...,...,...,...,...,...
450,451,0,5.8,73.6,9.1,0,1,0,54.2,77.9
674,675,0,4.7,93.5,7.2,1,1,0,49.1,83.8
763,764,0,2.2,68.6,5.7,1,1,0,58.3,81.2
556,557,0,4.5,87.7,7.6,1,1,0,71.7,80.8
620,621,0,4.8,85.0,7.4,1,1,0,78.2,98.3

In [ ]:
y_train

421    B
197    A
990    B
60     B
871    A
      ..
450    C
674    B
763    B
556    B
620    A
Name: final_grade, Length: 200, dtype: object

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
le = LogisticRegression(max_iter=100)

In [ ]:
le.fit(x_train,y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_predict = le.predict(x_test)

In [ ]:
y_predict

array(['B', 'A', 'A', 'C', 'B', 'A', 'A', 'A', 'C', 'A', 'B', 'A', 'A',
       'B', 'B', 'C', 'A', 'B', 'C', 'D', 'B', 'A', 'B', 'B', 'A', 'C',
       'A', 'C', 'B', 'A', 'D', 'C', 'B', 'B', 'B', 'C', 'A', 'C', 'C',
       'B', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'C', 'C', 'B', 'A', 'A',
       'A', 'A', 'A', 'A', 'A', 'C', 'B', 'B', 'A', 'A', 'A', 'B', 'C',
       'D', 'A', 'C', 'B', 'B', 'B', 'C', 'C', 'A', 'A', 'C', 'B', 'C',
       'D', 'A', 'B', 'B', 'B', 'A', 'A', 'A', 'C', 'C', 'A', 'C', 'D',
       'A', 'A', 'B', 'C', 'B', 'A', 'C', 'B', 'D', 'A', 'A', 'B', 'A',
       'C', 'A', 'B', 'A', 'B', 'B', 'C', 'C', 'B', 'C', 'A', 'A', 'A',
       'C', 'B', 'C', 'C', 'C', 'C', 'B', 'D', 'D', 'A', 'A', 'B', 'A',
       'B', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B', 'B', 'A', 'A', 'D',
       'B', 'B', 'A', 'B', 'B', 'C', 'D', 'B', 'C', 'B', 'C', 'B', 'D',
       'A', 'B', 'B', 'B', 'C', 'B', 'D', 'A', 'C', 'A', 'A', 'A', 'B',
       'B', 'B', 'C', 'B', 'A', 'B', 'A', 'A', 'C', 'B', 'B', 'A', 'B',
       'D', 'B', 'C', 'C', 'D', 'C', 'A', 'A', 'A', 'C', 'B', 'C', 'C',
       'A', 'B', 'B', 'B', 'A', 'C', 'B', 'C', 'B', 'A', 'A', 'B', 'A',
       'B', 'A', 'B', 'C', 'D', 'A', 'C', 'C', 'C', 'A', 'C', 'C', 'B',
       'A', 'A', 'D', 'C', 'B', 'C', 'A', 'C', 'B', 'A', 'B', 'B', 'C',
       'C', 'B', 'D', 'D', 'C', 'B', 'B', 'C', 'B', 'B', 'C', 'B', 'B',
       'D', 'B', 'B', 'A', 'B', 'D', 'A', 'C', 'B', 'C', 'A', 'C', 'B',
       'C', 'B', 'C', 'B', 'B', 'A', 'A', 'C', 'C', 'B', 'C', 'B', 'C',
       'A', 'B', 'A', 'D', 'A', 'B', 'C', 'C', 'C', 'A', 'B', 'A', 'A',
       'A', 'B', 'A', 'B', 'B', 'A', 'B', 'A', 'C', 'A', 'B', 'B', 'B',
       'B', 'A', 'C', 'B', 'B', 'C', 'D', 'B', 'B', 'B', 'B', 'A', 'B',
       'B', 'A', 'B', 'A', 'A', 'A', 'B', 'B', 'A', 'C', 'C', 'B', 'A',
       'A', 'C', 'B', 'B', 'D', 'A', 'C', 'C', 'D', 'A', 'A', 'B', 'A',
       'A', 'B', 'A', 'A', 'A', 'D', 'A', 'A', 'B', 'A', 'C', 'A', 'D',
       'C', 'B', 'C', 'A', 'D', 'A', 'B', 'A', 'B', 'B', 'A', 'B', 'A',
       'A', 'C', 'B', 'C', 'C', 'D', 'B', 'A', 'A', 'A', 'D', 'C', 'B',
       'B', 'B', 'A', 'C', 'C', 'A', 'C', 'A', 'C', 'B', 'C', 'C', 'A',
       'C', 'A', 'A', 'D', 'C', 'A', 'B', 'A', 'D', 'D', 'B', 'C', 'B',
       'A', 'A', 'C', 'D', 'A', 'B', 'A', 'B', 'B', 'C', 'B', 'B', 'B',
       'A', 'C', 'C', 'B', 'A', 'B', 'A', 'C', 'A', 'D', 'C', 'B', 'D',
       'A', 'A', 'C', 'B', 'B', 'D', 'D', 'D', 'B', 'C', 'C', 'B', 'A',
       'B', 'B', 'A', 'B', 'A', 'C', 'C', 'C', 'B', 'A', 'B', 'A', 'B',
       'C', 'A', 'B', 'A', 'A', 'B', 'C', 'A', 'A', 'B', 'C', 'B', 'C',
       'A', 'B', 'D', 'A', 'A', 'B', 'D', 'C', 'B', 'A', 'A', 'A', 'B',
       'B', 'C', 'A', 'C', 'B', 'B', 'A', 'C', 'D', 'A', 'C', 'C', 'A',
       'A', 'A', 'B', 'C', 'C', 'A', 'D', 'A', 'B', 'B', 'A', 'B', 'A',
       'A', 'C', 'B', 'C', 'A', 'B', 'A', 'C', 'A', 'C', 'C', 'D', 'C',
       'C', 'A', 'A', 'A', 'B', 'A', 'A', 'B', 'D', 'A', 'A', 'C', 'B',
       'A', 'A', 'A', 'D', 'A', 'B', 'A', 'A', 'B', 'C', 'A', 'C', 'B',
       'D', 'C', 'A', 'A', 'C', 'B', 'A', 'A', 'A', 'D', 'C', 'B', 'A',
       'A', 'B', 'B', 'A', 'A', 'A', 'A', 'D', 'C', 'D', 'C', 'B', 'A',
       'D', 'B', 'A', 'B', 'B', 'C', 'A', 'A', 'C', 'B', 'C', 'B', 'B',
       'A', 'A', 'B', 'C', 'B', 'A', 'C', 'D', 'A', 'A', 'A', 'C', 'B',
       'C', 'C', 'C', 'A', 'B', 'B', 'A', 'C', 'D', 'D', 'A', 'C', 'A',
       'B', 'A', 'B', 'B', 'D', 'B', 'C', 'A', 'A', 'D', 'C', 'B', 'A',
       'B', 'B', 'A', 'C', 'A', 'B', 'B', 'B', 'B', 'B', 'A', 'C', 'C',
       'A', 'B', 'B', 'B', 'B', 'C', 'A', 'A', 'C', 'C', 'C', 'A', 'A',
       'A', 'A', 'A', 'A', 'B', 'A', 'B', 'C', 'A', 'D', 'B', 'C', 'A',
       'B', 'D', 'A', 'C', 'A', 'C', 'B', 'B', 'C', 'C', 'D', 'D', 'B',
       'A', 'B', 'B', 'B', 'B', 'C', 'B', 'A', 'C', 'C', 'D', 'B', 'B',
       'C', 'A', 'D', 'B', 'A', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'A',
       'D', 'A', 'B', 'D', 'B', 'B', 'C', 'C', 'C', 'A', 'A', 'C', 'C',
       'A', 'A', 'B', 'A', 'D', 'A', 'D', 'D', 'C', 'A', 'B', 'C', 'A',
       'B', 'B', 'A', 'A', 'A', 'C', 'B', 'A', 'B', 'A', 'B', 'A', 'C',
       'B', 'D', 'D', 'B', 'B', 'B', 'B', 'A', 'C', 'B', 'B', 'A', 'B',
       'B', 'B', 'C', 'B', 'C', 'A', 'C', 'D', 'B', 'B', 'A', 'A', 'C',
       'C', 'B', 'A', 'C', 'B', 'D', 'C', 'A', 'B', 'C', 'A', 'C', 'B',
       'C', 'C', 'B', 'A', 'A', 'A', 'C', 'A', 'A', 'D', 'B', 'A', 'B',
       'C', 'C', 'A', 'A', 'B', 'A', 'B'], dtype=object)

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           A       0.55      0.68      0.61       218
           B       0.45      0.43      0.44       284
           C       0.52      0.47      0.50       211
           D       0.52      0.49      0.51        75
           F       0.00      0.00      0.00        12

    accuracy                           0.51       800
   macro avg       0.41      0.41      0.41       800
weighted avg       0.50      0.51      0.50       800

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))